quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${PG_URL}
quarkus.datasource.username=${PG_USER}
quarkus.datasource.password=${PG_PASSWORD}

quarkus.hibernate-orm.schema-management.strategy=none

quarkus.flyway.enabled=true
quarkus.flyway.migrate-at-start=true

quarkus.cache.type=caffeine
quarkus.cache.caffeine.temperature-alert.expire-after-write=PT5M

kafka.bootstrap.servers=${KAFKA_URL}

mp.messaging.incoming.temperature-alerts.connector=smallrye-kafka
mp.messaging.incoming.temperature-alerts.topic=sensor.temperature.alerts
mp.messaging.incoming.temperature-alerts.partitions=1
mp.messaging.incoming.temperature-alerts.value.deserializer=sandbox.consumer.application.service.TemperatureAlertDeserializer

