kafka.bootstrap.servers=${KAFKA_URL}

quarkus.kafka-streams.bootstrap-servers=${KAFKA_URL}
quarkus.kafka-streams.application-id=telemetry-service
quarkus.kafka-streams.topics=sensor.temperature.updated,sensor.temperature.alerts

mp.messaging.outgoing.temperature-updated.connector=smallrye-kafka
mp.messaging.outgoing.temperature-updated.topic=sensor.temperature.updated
mp.messaging.outgoing.temperature-updated.partition=3
mp.messaging.outgoing.temperature-updated.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.temperature-alerts.connector=smallrye-kafka
mp.messaging.outgoing.temperature-alerts.topic=sensor.temperature.alerts
mp.messaging.outgoing.temperature-alerts.partition=1
mp.messaging.outgoing.temperature-alerts.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

app.alerts.temperature-limit=20